name: ci-office-com-worflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v4
      - name: Install Java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Quarkus CLI
        run: |
          wget -O /tmp/quarkus-cli.zip https://github.com/quarkusio/quarkus/releases/download/1.15.2.Final/quarkus-cli-1.15.2.Final.zip
          unzip /tmp/quarkus-cli.zip -d /tmp/quarkus-cli
          sudo mv /tmp/quarkus-cli/quarkus/bin/quarkus /usr/local/bin/
        env:
          JAVA_HOME: ${{ matrix.java-version }}
      - name: Build
        run: quarkus build