name: ci-office-com-worflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v4

      - name: Install Java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test --console=plain

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: wellysonp/officecom-back:latest
          platforms: linux/amd64,linux/arm64

#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Build
#        id: build
#        uses: cloudposse/github-action-docker-build-push@main
#        with:
#          registry: registry.hub.docker.com
#          organization: "${{ github.event.repository.owner.login }}"
#          repository: "${{ github.event.repository.name }}"
#          login: "${{ secrets.DOCKERHUB_USERNAME }}"
#          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
#          platforms: linux/amd64,linux/arm64


