name: ci-office-com-worflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v4
      - name: Install Java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build -x test --console=plain